name: Build & Push Frontend Docker Image

on:
  push:
    paths:
      - 'service/frontend_dockerfile'
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURECR_REGISTRY }}
          username: ${{ secrets.AZURECR_USERNAME }}
          password: ${{ secrets.AZURECR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./service/frontend_dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.AZURECR_REGISTRY }}/trustme-frontend:latest
